CC = g++

all: GenerateRandomLocations

GenerateRandomLocations: GenerateRandomLocations.cpp
	$(CC) -O3 GenerateRandomLocations.cpp -o GenerateRandomLocations

clean:

realclean: clean
	rm -f GenerateRandomLocations
