ifndef REPO_ROOT
  REPO_ROOT = $(HOME)/dev/smash-cmu
endif

all:
	make -C $(REPO_ROOT)/DroneController v_rep

clean:
	make -C $(REPO_ROOT)/DroneController clean

realclean:
	make -C $(REPO_ROOT)/DroneController realclean
